### ISSUE TITLE
Allow the map to handle projects with more than one Project Type

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/civic-project-mapping#25]

**Comment by tangospring** [comment]
Design.
1. Remove color background from project titles. Make background light gray.
2. Add Project Type indicators (a horizontal stack of vertical bars 5px wide and 100% tall with 2px horizontal margin) to the left of the project title.  HTML/CSS: empty divs with project type background color could work.
3. Add Project Type indicators (a stack of bars) to project description. Format these bars the same way as Project type filter on top of the map.
