### ISSUE TITLE
Organizations with multiple locations, what is the best way to input and display.

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/civic-project-mapping#58]
An example would be BikeWalk where they have one administrative location, but multiple bike rental kiosks.

What should happen when a person 
- clicks "Show on map"
- clicks one of the rental kiosks pins

Should the detail have each location listed with it's own "Show on Map"

**Comment by tangospring** [comment]
This is generic approach. We can use two types of distinctly colored pins: headquarters and stations. The HQ pin displays general info. Station displays address and station specific info (if any exists).

Station specific pins can be displayed either right away, when someone clicks on "Show on map", or they can be enabled from the HQ popup (from "Show rental kiosks" button). The first approach makes sense for Civic Projects map, I think (there is no overlap with other kinds of project pins).
