### ISSUE TITLE
How does this relate to other neighborhood sites that are kinda Tinder?

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/civic-project-mapping#70]
https://mysidewalk.com/ and https://nextdoor.com

**Comment by tangospring** [comment]
Those two sites are more like Neighborhood-Dashboard, not kinda Tinder. 
Nextdoor.com, has an interesting sign-in workflow and they apparently figured out how to define neighborhood boundaries on a map from an address.

**Comment by ghost** [comment]
I see some differences and possibly some collaborations?  Let's discuss this further Monday.
